### ISSUE TITLE
WP_JSON_Comments missing

### ISSUE THREAD

**Issue by ekandreas** [jacklenox/picard-present#1]
After installing WP-API and activating the theme, the following error message appears:
Fatal error: Class 'WP_JSON_Comments' not found in /var/www/picard/wp-content/themes/picard-present/functions.php on line 163

**Comment by mathieuhays** [comment]
The theme is using the beta version of the WP-API plugin.
You can get it from the master branch on github : https://github.com/WP-API/WP-API/tree/master

**Comment by rachelbaker** [comment]
@EkAndreas The WordPress.org plugin version of the JSON REST API is a day (or two) from being released.  In the meantime you can download the files as a .zip from here: https://github.com/WP-API/WP-API/archive/1.2.zip
